loglevel: debug
cpus: 1
monitoring:
  port: 5555
protocols:
  grpc:
    enable: true
    host: 0.0.0.0
    port: 4312
    mocks_dir: "./grpc/mocks"
    protos_dir: "./grpc/protos"
    grpc_tls: false
injection:
  enable: false
